= Hawkular-Inventory

Hawkular-Inventory is the Inventory module for Hawkular - basically "The Registry" of
stuff in Hawkular.

Hawkular is a modular systems monitoring suite, that consists of several sub-projects for
storing of metrics, alerting on incoming events and more. Those projects are developed
in their own GitHub repositories and integrated in this project.


ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-inventory]
image:https://travis-ci.org/hawkular/hawkular-inventory.svg["Build Status", link="https://travis-ci
.org/hawkular/hawkular-inventory"]
endif::[]

== About Inventory

The project is divided into several modules

* api: the Java Api of Hawkular-Inventory
* impl: the Backend implementation of the Inventory service
* rest-servlet: A JAX-RS servlet implementation that provides a gateway to the Java Api. It creates a .war file that
contain the Java api and Implementation to be deployed into a WildFly server
* rest-test: Integration tests of the rest-api above

== Setup

The build currently runs inside a WildFly server, that has a H2-DB installed. You can use the following
snippet to configure this database:

[source,xml]
----
<datasource jta="true" jndi-name="java:/jdbc/HawkularDS" pool-name="HawkularDS" enabled="true" use-ccm="true">
    <connection-url>jdbc:h2:standalone/data/hawkular_db</connection-url>
    <driver-class>org.h2.Driver</driver-class>
    <driver>h2</driver>
    <security>
        <user-name>sa</user-name>
        <password>sa</password>
    </security>
    <validation>
        <validate-on-match>false</validate-on-match>
        <background-validation>false</background-validation>
    </validation>
    <timeout>
        <set-tx-query-timeout>false</set-tx-query-timeout>
        <blocking-timeout-millis>0</blocking-timeout-millis>
        <idle-timeout-minutes>0</idle-timeout-minutes>
        <query-timeout>0</query-timeout>
        <use-try-lock>0</use-try-lock>
        <allocation-retry>0</allocation-retry>
        <allocation-retry-wait-millis>0</allocation-retry-wait-millis>
    </timeout>
    <statement>
        <share-prepared-statements>false</share-prepared-statements>
    </statement>
</datasource>
----

The datasource files will then be created inside the `standalone/data/` directory:

----
wildfly-8.2.0.Final $ ls standalone/data/
content  hawkular_db.h2.db  timer-service-data  tx-object-store
----

To clean the database, just remove those `hawkular_db.h2*` files.

We will make some automated process available in the future.

== Logger

Hawkular-Inv uses Logger prefix `HAWKINV` for looging wiht JBoss-Logging.

Code ranges are
api: 1-999
impl:  1000-1999
rest-api : 2000-2999

== Rest-Tests

The rest-tests are not run by default as they need a running WildFly server with above setup.
To run them manually you can specify not to skip them

    mvn -Dmaven.test.skip=false test

== License

Hawkular-Inventory is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----




